name: payment_processing_service

networks:
  pp_net:
    name: payment_processing_network

volumes:
  postgres_data:
  postgres_config:
  rabbitmq_data:

services:
  migrations:
    image: payment-processing-service:local
    command: alembic upgrade head
    env_file:
      - .env
    depends_on:
      db_pg:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - pp_net
    restart: "no"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    image: payment-processing-service:local
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db_pg:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    restart: on-failure
    volumes:
      - .:/app
    networks:
      - pp_net
    dns:
      - 8.8.8.8
      - 1.1.1.1

  consumer:
    image: payment-processing-service:local
    command: python -m src.main.run_consumer
    env_file:
      - .env
    depends_on:
      db_pg:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    restart: on-failure
    volumes:
      - .:/app
    networks:
      - pp_net
    dns:
      - 8.8.8.8
      - 1.1.1.1

  db_pg:
    image: postgres:18-alpine
    shm_size: 128mb
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES__DB?POSTGRES__DB is required}
      POSTGRES_USER: ${POSTGRES__USER?POSTGRES__USER is required}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD?POSTGRES__PASSWORD is required}
    ports:
      - 9879:${POSTGRES__PORT?POSTGRES__PORT is required}
    networks:
      - pp_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 1s
    volumes:
      - postgres_data:/var/lib/postgresql
      - postgres_config:/etc/postgresql

  rabbitmq:
    image: rabbitmq:4-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ__USER?RABBITMQ__USER is required}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ__PASSWORD?RABBITMQ__PASSWORD is required}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ__VHOST:-/}
    ports:
      - "${RABBITMQ__PORT:-5672}:5672"
      - "${RABBITMQ__MANAGEMENT_PORT:-15672}:15672"
    networks:
      - pp_net
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_running" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
